name: Build and Release

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -D @types/node ts-node

      - name: Build
        run: |
          export NODE_OPTIONS=--max_old_space_size=4096
          npx electron-forge make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: replayhelper-${{ matrix.os }}
          path: |
            out/make/*.deb
            out/make/*.exe
            out/make/*.zip
